### ISSUE TITLE
Very odd 'X' coordinate spacing for a few letters using a Helvetica font

### ISSUE THREAD

**Issue by EimaMei** [ColleagueRiley/RFont#2]
Text using the Helvetica font in RFont usually looks fine, however in some instances some letters have very odd spacing that makes them look very awkward compared to the rest of the string. In the example below you can see that happening with the letter 'v', where it's off by a few pixels:
![image](https://github.com/ColleagueRiley/RFont/assets/69605234/5298f6a5-80ad-4d8d-86f7-cc081f2149fa)

Using LibreOffice Writer, this is how I expect the text to look more or less:
![image](https://github.com/ColleagueRiley/RFont/assets/69605234/3ccd1d50-1cc4-401f-b2d0-9431c62a39a9)

And it isn't only with 'v'. "Button" suffers from the same issue, alongside many other random combinations of words.
![image](https://github.com/ColleagueRiley/RFont/assets/69605234/a3409784-7769-4d25-ad6c-085e8b511e65)

**Comment by ColleagueRiley** [comment]
Thank you for filing the issue; I'll be looking into it now.

**Comment by ColleagueRiley** [comment]
I'm not fully sure what I changed, but the text looks like this when it renders now.
This looks a bit more proper.

![image](https://github.com/ColleagueRiley/RFont/assets/50218871/2e1072cc-9c9a-4600-900a-89f08c699681)

Also, it may not render exactly how another app might render text depending on the spacing. 
`RFont_draw_text_spacing` can be used to change the spacing used to render the text.

![image](https://github.com/ColleagueRiley/RFont/assets/50218871/a7bc937e-2bc7-4bb6-bdcf-979bb4106f52)

As for the extra lines being rendered (shown in the screen shots). I'm not sure why they came to be but they are not related to this specific issue at the very least.

**Comment by ColleagueRiley** [comment]
Update : One of the things i fixed it (and the thing that is causing the line bug as well) is by using floats for the x and y values.

**Comment by ColleagueRiley** [comment]
![image](https://github.com/ColleagueRiley/RFont/assets/50218871/aa6b73d9-af1e-49b5-9efa-40202c74bfd3)
![image](https://github.com/ColleagueRiley/RFont/assets/50218871/b6bb007e-8bdc-45af-9418-7c204c2eb04f)

What do you think of this? (extra lines fixed)

**Comment by EimaMei** [comment]
The ‘v’ in all of the provided images is still leaning more towards the ‘d’ letter compared to the ‘e’. You can see how ‘v’ in the LibreOffice Writer screenshot is very clearly centred between ‘d’ and ‘e’, while in RFont the issue still persists. In fact, the spacing is much larger than in the previous versions, making the oddity more obvious. Unfortunately the done changes didn’t fix the awkwardness for the ‘v’ letter in any major ways. However, I will say that ‘button’ looks looks pretty good now.

One last thing I would like to point out is that I noticed that the very last letter, being ‘e’, looks also suspiciously very awkward compared to ‘r’, so that should also get investigated.

**Comment by ColleagueRiley** [comment]
Again, use a valid comparison. Neither are using the same spacing.

**Comment by EimaMei** [comment]
The added spacing doesn’t matter. The issue is that the letter is leaning more towards the left, when it’s suppose to be in the centre. I might show this more clearly with an image later tonight.

**Comment by ColleagueRiley** [comment]
The letter is not leaning towards the left, compare the images. The E is leaning towards the right

**Comment by ColleagueRiley** [comment]
![image](https://github.com/ColleagueRiley/RFont/assets/50218871/05a27226-9e21-43d0-b9ea-5e02a0af5d59)

The issue should be fixed now, Mr. Chinz. :)
